# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/simon/Github/valkyrie

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/simon/Github/valkyrie

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simon/Github/valkyrie/CMakeFiles /home/simon/Github/valkyrie/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simon/Github/valkyrie/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named valkyrie

# Build rule for target.
valkyrie: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valkyrie
.PHONY : valkyrie

# fast build rule for target.
valkyrie/fast:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/build
.PHONY : valkyrie/fast

pch.o: pch.cpp.o

.PHONY : pch.o

# target to build an object file
pch.cpp.o:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/pch.cpp.o
.PHONY : pch.cpp.o

pch.i: pch.cpp.i

.PHONY : pch.i

# target to preprocess a source file
pch.cpp.i:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/pch.cpp.i
.PHONY : pch.cpp.i

pch.s: pch.cpp.s

.PHONY : pch.s

# target to generate assembly for a file
pch.cpp.s:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/pch.cpp.s
.PHONY : pch.cpp.s

src/build.o: src/build.cpp.o

.PHONY : src/build.o

# target to build an object file
src/build.cpp.o:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/build.cpp.o
.PHONY : src/build.cpp.o

src/build.i: src/build.cpp.i

.PHONY : src/build.i

# target to preprocess a source file
src/build.cpp.i:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/build.cpp.i
.PHONY : src/build.cpp.i

src/build.s: src/build.cpp.s

.PHONY : src/build.s

# target to generate assembly for a file
src/build.cpp.s:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/build.cpp.s
.PHONY : src/build.cpp.s

src/context.o: src/context.cpp.o

.PHONY : src/context.o

# target to build an object file
src/context.cpp.o:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/context.cpp.o
.PHONY : src/context.cpp.o

src/context.i: src/context.cpp.i

.PHONY : src/context.i

# target to preprocess a source file
src/context.cpp.i:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/context.cpp.i
.PHONY : src/context.cpp.i

src/context.s: src/context.cpp.s

.PHONY : src/context.s

# target to generate assembly for a file
src/context.cpp.s:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/context.cpp.s
.PHONY : src/context.cpp.s

src/for_statement.o: src/for_statement.cpp.o

.PHONY : src/for_statement.o

# target to build an object file
src/for_statement.cpp.o:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/for_statement.cpp.o
.PHONY : src/for_statement.cpp.o

src/for_statement.i: src/for_statement.cpp.i

.PHONY : src/for_statement.i

# target to preprocess a source file
src/for_statement.cpp.i:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/for_statement.cpp.i
.PHONY : src/for_statement.cpp.i

src/for_statement.s: src/for_statement.cpp.s

.PHONY : src/for_statement.s

# target to generate assembly for a file
src/for_statement.cpp.s:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/for_statement.cpp.s
.PHONY : src/for_statement.cpp.s

src/if_statement.o: src/if_statement.cpp.o

.PHONY : src/if_statement.o

# target to build an object file
src/if_statement.cpp.o:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/if_statement.cpp.o
.PHONY : src/if_statement.cpp.o

src/if_statement.i: src/if_statement.cpp.i

.PHONY : src/if_statement.i

# target to preprocess a source file
src/if_statement.cpp.i:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/if_statement.cpp.i
.PHONY : src/if_statement.cpp.i

src/if_statement.s: src/if_statement.cpp.s

.PHONY : src/if_statement.s

# target to generate assembly for a file
src/if_statement.cpp.s:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/if_statement.cpp.s
.PHONY : src/if_statement.cpp.s

src/node.o: src/node.cpp.o

.PHONY : src/node.o

# target to build an object file
src/node.cpp.o:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/node.cpp.o
.PHONY : src/node.cpp.o

src/node.i: src/node.cpp.i

.PHONY : src/node.i

# target to preprocess a source file
src/node.cpp.i:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/node.cpp.i
.PHONY : src/node.cpp.i

src/node.s: src/node.cpp.s

.PHONY : src/node.s

# target to generate assembly for a file
src/node.cpp.s:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/node.cpp.s
.PHONY : src/node.cpp.s

src/show_statement.o: src/show_statement.cpp.o

.PHONY : src/show_statement.o

# target to build an object file
src/show_statement.cpp.o:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/show_statement.cpp.o
.PHONY : src/show_statement.cpp.o

src/show_statement.i: src/show_statement.cpp.i

.PHONY : src/show_statement.i

# target to preprocess a source file
src/show_statement.cpp.i:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/show_statement.cpp.i
.PHONY : src/show_statement.cpp.i

src/show_statement.s: src/show_statement.cpp.s

.PHONY : src/show_statement.s

# target to generate assembly for a file
src/show_statement.cpp.s:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/show_statement.cpp.s
.PHONY : src/show_statement.cpp.s

src/text.o: src/text.cpp.o

.PHONY : src/text.o

# target to build an object file
src/text.cpp.o:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/text.cpp.o
.PHONY : src/text.cpp.o

src/text.i: src/text.cpp.i

.PHONY : src/text.i

# target to preprocess a source file
src/text.cpp.i:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/text.cpp.i
.PHONY : src/text.cpp.i

src/text.s: src/text.cpp.s

.PHONY : src/text.s

# target to generate assembly for a file
src/text.cpp.s:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/text.cpp.s
.PHONY : src/text.cpp.s

src/trim.o: src/trim.cpp.o

.PHONY : src/trim.o

# target to build an object file
src/trim.cpp.o:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/trim.cpp.o
.PHONY : src/trim.cpp.o

src/trim.i: src/trim.cpp.i

.PHONY : src/trim.i

# target to preprocess a source file
src/trim.cpp.i:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/trim.cpp.i
.PHONY : src/trim.cpp.i

src/trim.s: src/trim.cpp.s

.PHONY : src/trim.s

# target to generate assembly for a file
src/trim.cpp.s:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/trim.cpp.s
.PHONY : src/trim.cpp.s

valkyrie.o: valkyrie.cpp.o

.PHONY : valkyrie.o

# target to build an object file
valkyrie.cpp.o:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/valkyrie.cpp.o
.PHONY : valkyrie.cpp.o

valkyrie.i: valkyrie.cpp.i

.PHONY : valkyrie.i

# target to preprocess a source file
valkyrie.cpp.i:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/valkyrie.cpp.i
.PHONY : valkyrie.cpp.i

valkyrie.s: valkyrie.cpp.s

.PHONY : valkyrie.s

# target to generate assembly for a file
valkyrie.cpp.s:
	$(MAKE) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/valkyrie.cpp.s
.PHONY : valkyrie.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... valkyrie"
	@echo "... edit_cache"
	@echo "... pch.o"
	@echo "... pch.i"
	@echo "... pch.s"
	@echo "... src/build.o"
	@echo "... src/build.i"
	@echo "... src/build.s"
	@echo "... src/context.o"
	@echo "... src/context.i"
	@echo "... src/context.s"
	@echo "... src/for_statement.o"
	@echo "... src/for_statement.i"
	@echo "... src/for_statement.s"
	@echo "... src/if_statement.o"
	@echo "... src/if_statement.i"
	@echo "... src/if_statement.s"
	@echo "... src/node.o"
	@echo "... src/node.i"
	@echo "... src/node.s"
	@echo "... src/show_statement.o"
	@echo "... src/show_statement.i"
	@echo "... src/show_statement.s"
	@echo "... src/text.o"
	@echo "... src/text.i"
	@echo "... src/text.s"
	@echo "... src/trim.o"
	@echo "... src/trim.i"
	@echo "... src/trim.s"
	@echo "... valkyrie.o"
	@echo "... valkyrie.i"
	@echo "... valkyrie.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

